apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-uh0r
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-uh0r
    app.kubernetes.io/part-of: ci1t-830-0009-app
  name: devfile-sample-uh0r
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-uh0r
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-uh0r
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0009-tenant/ci1t-830-0009-app/devfile-sample-uh0r@sha256:eb80378b75442e2d2f88eefdc52d7ecbf5a51506efdc7e247d31a1546b37f4bc
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
